version: '3.5'
services:
  txt:
    image: planaria/txt:0.0.3
    stdin_open: true
    volumes:
      - ./mnt:/root/mnt
    environment:
      - NAME=
      - DESCRIPTION=
      - MINER_URL=https://www.ddpurse.com/openapi
      - 'MINER_HEADERS={"token": "561b756d12572020ea9a104c3441b71790acbbce95a6ddbf7e0630971af9424b"}'
      - TOKEN=
    ports:
      - "3013:3013"
    networks:
      - txt
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  txt:
    name: txt
